### ISSUE TITLE
Extra info in docs on configuring layouts 

### ISSUE THREAD

**Issue by earthwytch** [statamic/docs#1028]
I'm following the "**Organize by Type**" structure for laying out views as shown on the [Views page in the docs](https://statamic.dev/views).

This has caused an error for me.

I have a `main.antlers.html` in a `layouts` folder under views.
I have a `content.antlers.html` in a `templates` folder under views.

I have added a variable to the template page as it says in the docs:

```
---
layout: main
---
```

I get this message:

**View [layout] not found.**

I have tried:

- `layout: main`
- `layout: layouts.main`
- `layout: layouts/main`

But I still get the error message. I feel like I'm missing something super basic but can't find anything in the docs.

The Views page also says "__...but you're welcome to create other layouts and configure specific entries, whole sections, or the whole site to use those instead.__" Could this page please be fleshed out a bit more for eeejits like me, or linked to a page that already shows how to do this in a more detail? Maybe some examples under the "Organizing" section?

**Comment by jackmcdade** [comment]
You were so close — it actually is clear (IMO) but you might be channeling some v2 conventions. All you need to do is not organize into subfolders, or include the subfolder in your YAML.

With subfolder nesting:
```
layout: layouts.main
```

Without:
```
layout: main 
```
