### ISSUE TITLE
Control panel utilities docs appears to be out of date for Statamic 4

### ISSUE THREAD

**Issue by sunscreem** [statamic/docs#1052]
During the upgrade to Statamic 4, I found that this code (in a service provider) had stopped working:

```php
      Utility::make('activity-log')
            ->title('Activity log')
            ->description('View the recent log of the sync with Filemaker')
            ->action(ActivityLogController::class)
            ->icon('telescope')
            ->register();
```

In order to get it working I needed to change it to:

```php
       Utility::register('activity-log')
            ->title('Activity log')
            ->description('View the recent log of the sync with Filemaker')
            ->action(ActivityLogController::class)
            ->icon('list');
```

The docs about adding utilities still mention `::make` and the example talks about using `Utility::extend` which didn't work for me.

https://statamic.dev/extending/utilities#creating-a-utility

Also wondering if this breaking change is worth a mention in the [4.0 upgrade guide](https://statamic.dev/upgrade-guide/3-4-to-4-0)?

**Comment by jasonvarga** [comment]
Good find.

The old way became deprecated in 3.4, then in 4.0 we removed deprecations.

The docs were updated when 3.4 came out, but as you noted, there are still references to Utility::make() that were missed. We should update those. Thanks!

**Comment by jackmcdade** [comment]
Looks like these were updated in #1056.
