### ISSUE TITLE
Info missing about scheduling revisions

### ISSUE THREAD

**Issue by AlinChindea** [statamic/docs#1074]
Hello, 

The Revisions documentation page indicates that one can `schedule updates to your content`. However, there's no further information about this feature on that page. I've also noticed on your Youtube channel that in the video announcing the launch of Revisions and Working Copies, scheduling content updates was an option - https://youtu.be/KO8luPtKuyM?t=100. Wondering if that documentation page needs to be updated one way or another. Thanks you, Alin.

**Comment by duncanmcclean** [comment]
You can no longer schedule entries via the revision publish actions (that was changed in https://github.com/statamic/cms/commit/9dc8cb4e500342376b1bdc0471da3da4bdb2daf1).

Scheduling works [the same way it does without using revisions](https://statamic.dev/collections#dates). You just need to make sure the revision you have published is the version you want to go live.
