### ISSUE TITLE
Docs missing about the usage of fields for collection routing

### ISSUE THREAD

**Issue by n9iels** [statamic/docs#1075]
Hello,

After playing around a bit with the routes of a collection, if found out that you can use fields in a route. For example, if you have a _category_ field that is dropdown with string you can use a URL like `{category}/{slug}`. This was exactly what I was looking for, but the docs do not mention this anywhere.

Is this feature just undocumented? Or is this officially not supported and will there be no guarantee I will keep working? Either way, I think it will be useful to mention it in the docs somewhere.

**Comment by jackmcdade** [comment]
Hey there, glad you figured it out! It is actually documented, however, in the first paragraph of the Routing section of this page: https://statamic.dev/collections#routing
