### ISSUE TITLE
Docs for icons are a missing

### ISSUE THREAD

**Issue by kevnk** [statamic/docs#1076]
I'd love to add some sweet icons to my fieldsets, but I'm not finding any documentation on what icons are available or how to add them to a set. 

- I found there are a _TON_ of icons in `/vendor/statamic/cms/resources/svg/icons/`. That's nice. 
- From the Peak starter-kit, I see you can add the `icon` prop nested under the `set` prop in `/resources/fieldsets/page_builder.yaml`
- I found you can click the edit icon on a `set` of a replicator field to set an icon to the set
![image](https://github.com/statamic/docs/assets/1181420/c1aef4ce-179b-4ef9-8483-a55043af4bc2)

Here are the tasks I'd envision may go with this:

- [ ] Docs: A page to view all the available icons 
- [ ] Docs: Icons Page > Ability to search icons
- [ ] Docs: Icons Page > Ability to copy icon name

**Comment by jackmcdade** [comment]
The docs are here: https://statamic.dev/fieldtypes/icon

I don't think it's necessary to list all the icons etc in the docs — everything you're looking to do is right there in the field. You can see them all, search them, and copy the name.
