### ISSUE TITLE
Explain difference between replacing & re-uploading assets

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/docs#1078]
I've seen a few people get confused about what the difference is between these two actions.

Discord conversation: https://discord.com/channels/489818810157891584/489819906540568593/1125386952057827328

**Comment by jackmcdade** [comment]
Done. [0aeb0f5](https://github.com/statamic/docs/commit/0aeb0f5b5e038aa0ce4fb250dc00eadd1b26128e)
