### ISSUE TITLE
Manual install ???

### ISSUE THREAD

**Issue by nicolasmol** [statamic/docs#1101]
https://v2.statamic.com/installing#manual-installation
There is a section **Manual Installation** which has completely disappeared in: https://statamic.dev/installing
Of maybe it's me ???

Where is the Zip to **"Unzip files into your webroot"** as mentionned ?
The 4 directories recursively ?
The sample.htaccess ?

**Comment by jackmcdade** [comment]
There is no "manual" install anymore, you **must** use Composer to install now. Follow the instructions on that page and you'll be in good shape.

**Comment by nicolasmol** [comment]
Which means bye bye some shared hosters...Lost time again

**Comment by jackmcdade** [comment]
Yes, bye bye to shared hosting. They're not recommended in today's web — too many risks and downsides compared to the ridiculously cheap vps hosting (e.g. Digital Ocean) these days.
