### ISSUE TITLE
Bard field with image enabled doesn't work

### ISSUE THREAD

**Issue by bymazzeo** [statamic/docs#1122]
Hello,

I have an issue with the toolbar of the bard field. I do enable the image feature but then when I go to edit an entry the image button is missing.

Blueprint:
![Screenshot 2023-10-20 at 18 54 26](https://github.com/statamic/docs/assets/124627594/49bbc856-a7c3-4766-acb8-db4b51d3754c)

Field (Editor):
![Screenshot 2023-10-20 at 18 54 10](https://github.com/statamic/docs/assets/124627594/7b71e782-3583-4b04-a7dc-5b0706a815ab)

**Comment by duncanmcclean** [comment]
Have you set an "Asset Container" on the Bard field?

**Comment by bymazzeo** [comment]
Hey @duncanmcclean,

I did now and it works like a charm,

many thanks.

**Comment by duncanmcclean** [comment]
Awesome! 

I'll keep this issue open - we should probably add a note about that to the documentation.

**Comment by jordigasau** [comment]
Sounds as a great idea. I would add a default config value too, like when you use an assets field.

Thanks!
