### ISSUE TITLE
Addition to quick start troubleshooting page

### ISSUE THREAD

**Issue by bridgebrain** [statamic/docs#1127]
I had an issue that took a few hours to figure out, which should probably be in the troubleshooting page for quick start. 

I was installing a fresh copy of statamic to a server (hostinger) inside public_html, and no matter what I did nothing would display at the address. 

I needed to build the .htaccess and index.php pages from scratch, because the local system assumes you're using localhost and artisan serve, and the deployment guides assume you're using resources that do automatic configuration.

**Comment by marcorieser** [comment]
Sounds like the webroot in your hosting was set to / instead of /public.

**Comment by duncanmcclean** [comment]
We're using the same [default `.htaccess` file](https://github.com/laravel/laravel/blob/11.x/public/.htaccess) as Laravel has, which hasn't changed in years. I've also used it in other hosting setups with Apache without any issues. 

What changes did you need to make to your `.htaccess` file to get it working?

**Comment by duncanmcclean** [comment]
The default `.htaccess` has been copied directly from Laravel, so should work fine for most sites. 

Since you haven't provided any additional context around what you needed to change and we haven't had anyone else run into this issues, I'm going to close this issue.
