### ISSUE TITLE
Add docs for specifying additional upload-able extensions

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/docs#1175]
Related: statamic/cms#9037

Also, documenting the workaround [from this reply](https://github.com/statamic/cms/issues/9182#issuecomment-1850809448) might be helpful.

**Comment by conradfuhrman** [comment]
Would love to see an addition like:

```
mimes: 
   - application/glb-glob
   - misc/file-only-I-use
```

For the individual asset buckets.
