### ISSUE TITLE
Clarify, if necessary, the time fieldtype uses `<input type="time">` to show either a 12 or 24-hour view of the time

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/docs#1267]
The actual value is not changing, but changing to the native HTML `time` input type allows for a user to see either or, depending what their locale is!

Related to statamic/cms#9662

**Comment by duncanmcclean** [comment]
Thanks for opening this issue!

However, I don't know that we actually need to change anything on the docs for this change since it was mostly a UI improvement.
