### ISSUE TITLE
Amp folder structure error

### ISSUE THREAD

**Issue by marflow** [statamic/docs#129]
Small thing on statamic.dev/amp: In the folder illustration, the second "blog /" folder should be one level up. 

resources/views/
|-- amp/
|   |-- blog/
|   |--   |-- index.antlers.html
|   |--   |-- show.antlers.html
|   |-- blog/
|   |--   |-- index.antlers.html
|   |--   |-- show.antlers.html

(Or I have to read that part of the docs again?)

**Comment by jasonvarga** [comment]
You’re absolutely right. Thanks for pointing it out.
