### ISSUE TITLE
Document new `attribute` modifier

### ISSUE THREAD

**Issue by potsky** [statamic/docs#1296]
Goes along with statamic/cms#9796

Hint for the documentation ;-)

---
id: 
blueprint: modifiers
modifier_types:
  - markup
title: Attribute
---

Attribute modifier conditionally renders the parameter that corresponds to the given value, but only when this provided value is not empty.

For example:

```antlers
---
var: text-pink-500 bg-yellow-200
---

<span{{ view:var | attribute:class }}>Statamic</span>
```

returns:

```html
<span class="text-pink-500 bg-yellow-200">Statamic</span>
```

But

```antlers
---
var: 
---

<span{{ view:var | attribute:class }}>Statamic</span>
```

will returns:

```html
<span>Statamic</span>
```

**Comment by duncanmcclean** [comment]
Documented in ba2ea9e.
