### ISSUE TITLE
Herd installation instructions incomplete

### ISSUE THREAD

**Issue by hobyvh** [statamic/docs#1297]
Following the directions there are a couple things that should be included:

1. After installing the Statamic CLI, we're told to issue the "statamic new" command, which responds with an error. The CLI doesn't add itself to my shell, so the instructions on page https://statamic.dev/troubleshooting/command-not-found-statamic need to be referenced.
2. There is no mention that "statemic new" will create the site in the directory your shell is currently in, so there should be instruction to go into the ~Herd/ folder and issue the command there.

**Comment by joshuablum** [comment]
Thanks! Should be more clear now :)
