### ISSUE TITLE
No docs page for `width` fieldtype

### ISSUE THREAD

**Issue by sjclark** [statamic/docs#1313]
As per title 🤷 
https://statamic.dev/fieldtypes/width

**Comment by joshuablum** [comment]
Duplicate of https://github.com/statamic/docs/issues/1150.

Thanks Sam, will be added shortly!

**Comment by sjclark** [comment]
😂  whoops, not sure how I missed that!

**Comment by joshuablum** [comment]
It happens, no worries 😌
