### ISSUE TITLE
The use of Query Scope could be explained more clearly.

### ISSUE THREAD

**Issue by simonbedard12** [statamic/docs#1335]
For the Query Scope to function inside the collection tag, it must be called using the underscore syntax, even if the class name uses camel case, which is fine.

<img width="819" alt="query_scope-2" src="https://github.com/statamic/docs/assets/20709665/cf3d9a11-2d25-4aad-99ac-5682c181911c">

_Only the one on the left is working_

However, this could be more explicitly stated in the documentation.

https://statamic.dev/fieldtypes/entries#options
https://statamic.dev/extending/query-scopes-and-filters#scopes

Additionally, the default PHP comment could be updated to provide an example when creating a scope with the CLI command `php please make:scope`.

```php
/*
* @use: my_query_scope
/*
class MyQueryScope extends Scope{
...
```

**Comment by duncanmcclean** [comment]
This will be improved by statamic/cms#9933, which will allow you to select from available query scopes in your app, without needing to manually specify their handles.
