### ISSUE TITLE
Style issue for sticky header

### ISSUE THREAD

**Issue by Web10-Joris** [statamic/docs#1360]
The background-color on header is not full width. Looks odd once you get to the footer :) (1440vw) 

<img width="1440" alt="Scherm­afbeelding 2024-05-31 om 18 17 30" src="https://github.com/statamic/docs/assets/129582223/428fe532-4872-462b-b3f3-e3db351480cf">

**Comment by jackmcdade** [comment]
I can't recreate that – looks perfect to me. What browser are you using?

**Comment by jackmcdade** [comment]
Oh nevermind, I saw it as a Dark Mode issue — definitely have that on the brain. Got it.
