### ISSUE TITLE
Wrong invalidation array nest examples?

### ISSUE THREAD

**Issue by johncarter-** [statamic/docs#1368]
I'm a bit confused. Are the invalidation config arrays wrong?

For example:

https://github.com/statamic/docs/blob/master/content/collections/docs/static-caching.md?plain=1#L418-L423

```php
return [
    'class' => null,
    'invalidation' => [
        'rules' => 'all',
    ]
];
```

Should read:
```php
return [
    //... 
    'invalidation' => [

        'class' => null,

        'rules' => 'all',

    ],
    //... 
];
```

**Comment by duncanmcclean** [comment]
Will be fixed by #1366.
