### ISSUE TITLE
Scope name convention not documented

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/docs#1384]
When following the scope guide here:
https://statamic.dev/extending/query-scopes-and-filters#scopes

It does not tell you that after making the scope in order to use it you need to use the snake case version of the class name.

It doesn't tell you that on the collection tag docs either:
https://statamic.dev/tags/collection#custom-query-scopes

**Comment by godismyjudge95** [comment]
@duncanmcclean not sure this is fully resolved as that PR only addresses the query scopes for the fieldtypes and not the collection tag?

For example on this page https://statamic.dev/tags/collection#custom-query-scopes there is nothing documenting that I must use underscores when using:
```
{{ collection:blog query_scope="your_query_scope" }}
```

Also perhaps there should be a note on https://statamic.dev/extending/query-scopes-and-filters#scopes so when people go to create their scope they can see the note that in order to use it they must convert the case?

**Comment by duncanmcclean** [comment]
Sorry, I missed the bit about the collection tag docs, updated!
