### ISSUE TITLE
Anywhere editing /app/console/kernal.php is mentioned needs to be updated to Laravel 11

### ISSUE THREAD

**Issue by twd3** [statamic/docs#1447]
I was just reading how to schedule git commits and the docs are out of date. The current docs probably need to stay for Laravel 10 users but for Laravel 11 there should be a note that talks about how you put the code in /routes/console.php now and the syntax is like this:
```Schedule::command('statamic:git:commit')->weekdays()->twiceDaily(1, 13)->timezone('America/Denver');```

Sorry I tried to do a PR to the docs but got confused. I have to compare or something before I can do a PR? I tried...lol

**Comment by duncanmcclean** [comment]
Thanks for pointing it out - I've updated the docs: https://statamic.dev/git-automation#scheduling-commits
