### ISSUE TITLE
Search Result tag : "result type" is an entry id, not a predefined "type" 

### ISSUE THREAD

**Issue by dadaxr** [statamic/docs#1454]
In the [doc](https://statamic.dev/tags/search#variables) it's said : 

![image](https://github.com/user-attachments/assets/7c4a61ca-b6e4-406d-87c8-1d32461f73b0)

But it appears to be the entry id ... 
![image](https://github.com/user-attachments/assets/ee20e82b-c6b9-4755-b0bc-3ea2270408cd)

So we have to fetch it to know more : 

```
{{ search:results }}
 {{ res = {get_content :from="result_type"}|first }}
 {{ res.collection.handle|dump }}
 or using some modifier like 
  {{ res.collection.handle|is_entry }}
  {{ res.collection.handle|is_asset }}
  {{ res.collection.handle|is_term }}
  {{ res.collection.handle|is_image }}
{{ /search:results }}
...
```
Dont know if it is an issue or just a doc not updated ... ?

**Comment by duncanmcclean** [comment]
`{{ result_type }}` seems to be outputting as expected for me: 🤔

![CleanShot 2024-09-16 at 12 51 58](https://github.com/user-attachments/assets/db6c5977-dfac-48e7-9750-f7f9d3cb8684)

This is the code I'm using:

```antlers
{{ search:results index="default" }}
    {{ title }} - {{ result_type }}<br>
{{ /search:results }}
```

Is there any reason you're using the `{{ get_content }}` tag inside the results loop?

**Comment by dadaxr** [comment]
I'm using the get_content just to illustrate how to fetch the ids the "result_type" is returning to me ... 

But I know the reason : I'm using  : supplement_data="false"

```
{{ search:results supplement_data="false" index="site_search" limit="8" }}
 
  {{ if no_results }}
    <h2>No results.</h2>
  {{ else }}
    {{ result_type }}
    <a href="{{ url }}" class="result">
      <h2>{{ title|mark }}</h2>
      <p>{{ content | truncate:240 }}</p>
    </a>
  {{ /if }}
 
{{ /search:results }}

```

when using supplement_data="true" , I get the expected resultat (entry, term, ...)

could worth mentioning it ..?

**Comment by duncanmcclean** [comment]
Oh, you're using `supplement_data="false"`, that'll be why. 

I've updated the section around "supplementing data" to mention that.
