### ISSUE TITLE
https://statamic.dev/extending/fieldtypes

### ISSUE THREAD

**Issue by AtmoFX** [statamic/docs#1525]
Hello,

I have recently tried my hand on https://statamic.dev/extending/fieldtypes, to see if I was able to extend statamic.<br/>
To people like me who are having their very first web development on Statamic, some of the obvious things to you guys are not obvious at all. I felt being a little bit more verbose for the password introductory example could have saved me from hours of cargo cult programming.

Below is my humble suggestion to improve the help page, with:
 - A prerequisite list of actions to execute before creating the first field, with an addition and links to the relevant sections in other help pages.
 - The list of (default) files that need editing when creating a new fieldtype.
 - 2-3 things were moved or removed from the example.
   For instance, the PHP snippet under `php please make:fieldtype TogglePassword`, with no comments in the current help page, left me wonder what I was supposed to do with it more time than I want to publicly admit.

... hopefully nothing too crazy.

Let me know if you think that is useful.

------

## Registering

Any fieldtype classes inside the `App\Fieldtypes` namespace will be automatically registered.

To store them elsewhere, manually register an action in a service provider by calling the static `register` method on your action class.

``` php
public function boot()
{
    Your\Fieldtype::register();
}
```

## Creating

Fieldtypes have two pieces:

  - A PHP class handling data processing and validation
  - A Vue 2 component handling the view and data binding

For this example we will create a password field with a "show" toggle control:

<figure>
    <img src="/img/example-password-fieldtype.png" alt="An example fieldtype that reveals a password field" class="p-4 bg-white" width="477">
    <figcaption>Follow along and you could make this!</figcaption>
</figure>

### Prerequisites

If this is the first fieldtype you are creating, you will need to:

 1. Add the following to the `devDependencies` in `package.json`.
    ``` js
    "devDependencies": {
        "@tailwindcss/typography": "^0.5.12",
        "autoprefixer": "^10.4.19",
        "laravel-vite-plugin": "^1.0.2",
        "postcss": "^8.4.38",
        "tailwindcss": "^3.4.3",
        "@vitejs/plugin-vue2": "^2.3.1", // [tl! ++]
        "vite": "^5.2.8"
    }
    ```
 2. Install the new dependency.
 3. Create the files: `resources/js/cp.js` and `resources/css/cp.css`.
 4. Inside `app/Providers/AppServiceProvider.php`, add the path to both files in the `public function boot(): void` (see the ["_Using vite_" help section](/extending/control-panel#using-vite)).
 In most situations, you may only need to uncomment the function's body.
 5. Inside `vite.config.js` uncomment the lines as highlighted in the ["_Adding assets to your build process_" help section](/extending/control-panel#adding-assets-to-your-build-process).

### Creating the field

Create a fieldtype PHP class and Vue component by running the following command:

``` shell
php please make:fieldtype <Your fieldtype class name>
```

This creates the following:
 - An `app/FieldTypes/<class name>.php` file with a pre-filled class inside it.
 - A `resources/js/components/fieldtypes/<class name>.vue` file.

Your component has two requirements:

- It must expect a `value` prop.
- It must emit an `input` event whenever the value updates.

Statamic provides you with a `Fieldtype` mixin that does this automatically to reduce boilerplate code.

At this point, coding will take place in the following 4 files, the first 2 of which are shared across all the fieldtypes you create:

 - `resources/js/cp.js`
 - `resources/css.cp.css`
 - `app/FieldTypes/<class name>.php`
 - `resources/js/components/fieldtypes/<class name>.vue`

Refer to the language written in each of the code snippets below to find out what file to edit.

### Example Vue component

As the first example, the `TogglePassword` class will not require editing all 4 of the above files.

Create it using the command below:

``` shell
php please make:fieldtype TogglePassword
```

Register your Vue component as `[handle]-fieldtype`:

``` js
import Fieldtype from './components/fieldtypes/TogglePassword.vue';

Statamic.booting(() => { 
  // Should be named [snake_case_handle]-fieldtype
  Statamic.$components.register('toggle_password-fieldtype', Fieldtype);
});
```

The component in this example is defined by the code:

``` vue
<template>
    <div>
        <text-input :type="inputType" :value="value" @input="updateDebounced" />
        <label><input type="checkbox" v-model="show" /> Show Password</label>
    </div>
</template>

<script>
export default {
    mixins: [Fieldtype],
    data() {
        return {
            show: false
        };
    },
    computed: {
        inputType() {
            return this.show ? 'text' : 'password';
        }
    }
};
</script>
```

Finally, build the component:

``` shell
npm run build
```

#### Example walk-through:
- The `Fieldtype` mixin is providing an `value` prop containing the initial value of the field.
- The `text-input` component emits an `input` event whenever you type into it. Our component is listening for that event and calls the `update` method.
- The `Fieldtype` mixin is providing an `updateDebounced` method which emits the required `input` event. This is how the parent component is detecting changes in your fieldtype.

:::warning
**Do not** modify the `value` prop directly. Instead, call `this.update(value)` (or `this.updateDebounced(value)`) and let the Vuex store handle the update appropriately.
:::

## Fieldtype Icon

You can use an existing SVG icon from Statamic's `resources/svg` directory by passing it's name into an `$icon` class variable, by returning a full SVG as a string, or returning it as a string from the `icon()` method.

```php
<?php

class CustomFieldtype extends Fieldtype
{
    protected $icon = 'tags';
    // or
    protected $icon = '<svg> ... </svg>';
    // or
    function icon()
    {
        return file_get_contents(__DIR__ . 'resources/svg/left_shark.svg');
    }
}
```

## Fieldtype Categories

When using the blueprint builder inside the control panel, your fieldtype will be listed under the `special` category by default. To move your fieldtype into a different category, define the `$categories` property on your class:

```php
<?php

class CustomFieldtype extends Fieldtype
{
    public $categories = ['number'];
}
```

You can select from any of the keys available in the `FieldtypeSelector`:
- `text`
- `controls`
- `media`
- `number`
- `relationship`
- `structured`
- `special`

## Configuration Fields

You can make your fieldtype configurable with configuration fields. These fields are defined by adding a `configFieldItems()` method on your PHP class that returns an array of fields.

``` php
protected function configFieldItems(): array
{
    return [
        'mode' => [
            'display' => 'Mode',
            'instructions' => 'Choose which mode you want to use',
            'type' => 'select',
            'default' => 'regular',
            'options' => [
                'regular' => __('Regular'),
                'enhanced' => __('Enhanced'),
            ],
            'width' => 50
        ],
        'secret_agent_features' => [
            'display' => 'Enable super secret agent features',
            'instructions' => 'Can you even handle these features?',
            'type' => 'toggle',
            'default' => false,
            'width' => 50
        ],
    ];
}
```

The configuration values can be accessed in the Vue component using the `config` property.

``` js
return this.config.mode; // regular
```

### Options

| Key | Definition |
|---|---|
| **display** | The field's display label |
| **instructions** | Text shown underneath the display label. Supports Markdown. |
| **type** | Name of the fieldtype used to manage the config option. |
| **default** | An optional default value. |
| **width*
| ***other*** | Some fieldtypes have additional configuration options available. |

:::tip
A little code diving will reveal all the possible config options for each field type. Look for the `configFieldItems()` method in each class here: <https://github.com/statamic/cms/tree/3.3/src/Fieldtypes>
:::

### Adding configuration fields to existing fieldtypes

Sometimes you may want to add a config field to another fieldtype rather than creating a completely new one.

You can do this using the `appendConfigField` or `appendConfigFields` methods on the respective fieldtype.

```php
use Statamic\Fieldtypes\Text;

// One field...
Text::appendConfigField('group', [
  'type' => 'text',
  'display' => 'Group',
]);

// Multiple fields...
Text::appendConfigFields([
  'group' => ['type' => 'text', 'display' => '...',],
  'another' => ['type' => 'text', 'display' => '...',],
]);
```

## Meta Data

Fieldtypes can preload additional "meta" data from PHP into JavaScript. This can be anything you want, from settings to eager loaded data.

``` php
public function preload()
{
    return ['foo' => 'bar'];
}
```

This can be accessed in the Vue component using the `meta` property.

``` js
return this.meta; // { foo: bar }
```

If you have a need to update this meta data on the _JavaScript side_, use the `updateMeta` method. This will persist the value back to Vuex store and communicate the update to the appropriate places.

``` js
this.updateMeta({ foo: 'baz' });
this.meta; // { foo: 'baz' }
```

### Example use cases -

Here are some reasons why you might want to use this feature:

- The assets and relationship fieldtypes only store IDs, so they will fetch item data using AJAX requests. If you have many of these fields in one form, you'd have a bunch of AJAX requests fire off when the page loads. Preload the item data to avoid the initial AJAX requests.
- Grid, Bard, and Replicator fields all preload values for what a new row/set contains, plus the recursive meta values of any nested fields.

## Replicator Preview

When [Replicator](/fieldtypes/replicator) (or [Bard](/fieldtypes/bard)) sets are collapsed, Statamic will display a preview of the values within it.

By default, Statamic will do its best to display your fields value. However, if you have a value more complex than a simple string or array, you may want to customize it.

You may customize the preview text by adding a `replicatorPreview` computed value to your Vue component. For example:

``` js
computed: {
    replicatorPreview() {
        return this.value.join('+');
    }
}
```

:::tip
This _does_ support returning an HTML string so you could display image tags for a thumbnail, etc. Just be aware of the limited space.
:::

## Index Fieldtypes

In listings (collection indexes in the Control Panel, for example), string values will be displayed as a truncated string and arrays will be displayed as JSON.

You can adjust the value before it gets sent to the listing with the `preProcessIndex` method:

``` php
public function preProcessIndex($value)
{
    return str_repeat('*', strlen($value));
}
```

If you need extra control or functionality, fieldtypes may have an additional "index" Vue component.

``` js
import Fieldtype from './TogglePasswordIndexFieldtype.vue';

// Should be named [snake_case_handle]-fieldtype-index
Statamic.$components.register('toggle_password-fieldtype-index', Fieldtype);
```

``` vue
<template>
    <div v-html="bullets" />
</template>

<script>
export default {
    mixins: [IndexFieldtype],
    computed: {
        bullets() {
            return '&bull;'.repeat(this.value.length);
        }
    }
}
</script>
```

The `IndexFieldtype` mixin will provide you with a `value` prop so you can display it however you'd like. Continuing our example above, we will replace the value with bullets.

## Augmentation

By default, a fieldtype will not perform any augmentation. It will just return the value as-is.

You can customize how it gets augmented with an augment method:

``` php
public function augment($value)
{
    return strtoupper($value);
}
```

[Read more about augmentation](/extending/augmentation)

## Accessing Other Fields

If you find yourself needing to access other form field values, configs, etc., you can reach into the publish form store from within your Vue component: 

```js
inject: ['storeName'],

computed: {
    formValues() {
        return this.$store.state.publish[this.storeName].values;
    },
},
```

## Updating from v2

In Statamic v2 we pass a `data` prop that can be directly modified. You might be see something like this:

``` html
<input type="text" v-model="data" />
```

In v3 you need to pass the value _down_ in a prop (call it `value`), and likewise pass the modified value _up_ by emitting an `input` event. This change is the result of architectural changes in [Vue.js 2](https://vuejs.org).

``` html
<!-- Using a standard HTML input field: -->
<input type="text" :value="value" @input="$emit('input', $event.target.value)">

<!-- Using the "Fieldtype" mixin's `update` method to emit the event for you: -->
<input type="text" :value="value" @input="update($event.target.value)">

<!-- Using a Statamic input component to clean it up even further: -->
<text-input :value="value" @input="update">
```

An alternate solution could be to add a `data` property, initialize it from the new `value` prop, then emit the event whenever the `data` changes. By doing this, you won't need to modify your template or the rest of your JavaScript logic. You can just continue to modify `data`.

``` vue
<template>
    <input type="text" v-model="data" />
</template>
<script>
export default {
    mixins: [Fieldtype],
    data() {
        return {
            data: this.value,
        }
    },
    watch: {
        data(data) {
            this.update(data);
        }
    }
}
</script>
```

If you had a `replicatorPreviewText` method, it should be renamed to `replicatorPreview` and moved to a computed.

The PHP file should require no changes.

**Comment by jasonvarga** [comment]
Thanks for this.

As far as I can tell, the confusing part that you've tried to address is that the fieldtype page itself doesn't really go into detail about setting up your JS+build process. Is that right?

**Comment by AtmoFX** [comment]
Well... there certainly was confusion on my end but I am not sure this is going to be useful now that you updated the article.
However, I would like to discuss about documentation for beginners from a more general perspective.

I am sure this will come as pedantic (despite my effort) so feel free to ignore it.

-----

From the type of tutorial it is, I would say this page is typically directed at beginners. Actually, this is for first-timers as anyone, even if still beginners, who already created their own field and confirmed it works have no use for copy-our-example-to-see-how-it-works instructions anymore. I think it misses its mark though (even now).

As someone whose job used to include the redaction of documentation, I classify information into what is useful, distracting or undetermined (for lack of a better word). The "undetermined " appears as neither useful nor distracting or rather, in the grand signal-to-noise scheme of things, different people classify it as signal or as noise.
I generally consider beginners have fewer memory items, a bigger need for an exhaustive checklist and will see more of these undetermined points as signal, so they should not be excluded. In fact, only the blattantly off-topic (and hardly anything else) should be put in the "disctracting" category and excluded from the beginners' help.


One telling example: between my suggestion and your version, I see you removed a link in the "Prerequisites" section, supposedly to decrease the noise (let me know if I am wrong assuming that).

I (and I think everyone trying to create their first fieldtype) was prepared to invest time to read detailed, very technical documentation but I sure would have traded the hours of browsing through entire webpages for the exhaustive list of relevant sections, linked directly from the procedure.

That was the goal of my "Prerequisites" section suggestion: include it but let people know it may be skipped unless "*this is the first fieldtype [they] are creating*".

BTW, the same can be said about editing `package.json` in the same section. Maybe you are like: "of course you have to edit it, duh!" but:
 - That is all but obvious to me (which is why the info comes from Erin, who helped me big time on Discord and not from my hours of browsing the doc).
 If this was required for custom fieldtypes, I for one do not understand how the "native" fields (AFAICT, also based on vue) work without.
 - Are you sure nothing, not even the version, is useful in that snippet?
 - Are you sure turning an exhaustive checklist into a non-exhaustive one is worth decreasing the noise?

-> I leave that to your evaluation.

PS: In case you wonder how it could possibly have taken me hours, I can explain easily:
 - Without an explicit, exhaustive list, there is no way to tell beforehand all the changes you have to do to make it work. and yes, the items exist somewhere in the documentation but there is no telling where without reading the corresponding pages.
 On top of that, once you have changed everything you need, there is no telling that was all. The best you can do is read almost all the pages until you are confident enough you applied everything needed.
 - When the fieldtype did not work, I went back through everything again (and several times over as I was in fact going in circles).

**Comment by AtmoFX** [comment]
Hey @jasonvarga 

Just one tiny additional comment since I am actually using what I learned starting today: `php please make:fieldtype ABC` shows this message:

```
  ⇂ Don't forget to import and register your fieldtype's Vue component in resources/js/addon.js
  ⇂ For more information, see the documentation: https://statamic.dev/fieldtypes#vue-components
```

Just wanted to highlight `addon.js` is not consistent with the `cp.js` from the documentation.
