### ISSUE TITLE
Document "Clearable" option on Button Group fieldtype

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/docs#1542]
Related: https://github.com/statamic/cms/pull/11110

**Comment by caseydwyer** [comment]
@duncanmcclean I meant to bundle this in with the original PR, and totally forgot. 🤦‍♂️ Sorry about that! Want me to take a crack at adding this to the Button Group docs?

**Comment by duncanmcclean** [comment]
No problem! 

Sure - otherwise, we can handle it at some point.
