### ISSUE TITLE
Highlighting in dark mode is unreadable

### ISSUE THREAD

**Issue by andjsch** [statamic/docs#1545]
![grafik](https://github.com/user-attachments/assets/ca21d2cb-61e4-49e0-b568-bd9d89f1dd3d)

Using Firefox 132

**Comment by SuperHydroman** [comment]
![image](https://github.com/user-attachments/assets/bcb78bc9-2265-4e82-b418-78c300146438)
![image](https://github.com/user-attachments/assets/452ac95d-9cbc-4d53-9d23-b0510ade56d0)
I have no problems with this on my macbook

**Comment by andjsch** [comment]
Interesting. I am using Firefox as my primary browser. I see that Chrome and Safari don't seem to recognize the custom highlighting. The highlighting seems intentional as of this [line in the code](https://github.com/statamic/docs/blob/60a4f9d886f697b5ac0ca8af2a178712f922b1e5/resources/css/content.css#L4). I'll submit a PR.

**Comment by andjsch** [comment]
My bad. But Jason took care of it already.
