### ISSUE TITLE
Structure vs Nav docs confusion

### ISSUE THREAD

**Issue by fitzage** [statamic/docs#186]
1. The [core concepts Structure page](https://statamic.dev/structures) says to use the structure tag in your template, and links to [a page that doesn’t exist](https://statamic.dev/tags/structure).

This is the example code:

```
<ul>
{{ structure:top_nav }}
    <li><a href="{{ url }}">{{ title }}</a></li>
{{ /structure:top_nav }}
</ul>
```

2. The [Nav Tag page](https://statamic.dev/tags/nav) seems to indicate that structures should be accessed using the nav tag.

My guess is that the Structures page needs to be rewritten? But maybe there just needs to be a page for a structure tag if such a thing exists?

**Comment by jackmcdade** [comment]
This has been addressed.
