### ISSUE TITLE
API now Facades

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/docs#19]
In the upgrade guide...

Statamic\API classes are now Statamic\Facades

In the OAuth area it is still using Statamic\API

**Comment by jimmypuckett** [comment]
I see a conflict in the docs for the [custom user repository page](https://statamic.dev/knowledge-base/storing-users-somewhere-custom), that references `Statamic\API\User::repository` in the docs, but `Statamic\Facades\User::repository` in the code block, so I guess that is why there is a conflict?

I opened an issue in the cms repo about the method not working...

https://github.com/statamic/cms/issues/1046

but I thought that it would be good to link the doc issue here too.
