### ISSUE TITLE
z-index on search typeahead lets it fall behind page content

### ISSUE THREAD

**Issue by brendanfalkowski** [statamic/docs#192]
<img width="1270" alt="Screen Shot 2020-08-28 at 9 59 23 PM" src="https://user-images.githubusercontent.com/214924/91629016-f2150580-e979-11ea-8bf7-85a321a9a6d2.png">

**Comment by jonassiewertsen** [comment]
Thanks for the feedback @brendanfalkowski !

The search typehead has already been optimized and all results should be visible now.
![Screenshot 2020-09-18 at 01 52 57](https://user-images.githubusercontent.com/38906163/93539682-ccb06180-f951-11ea-8c19-1c466be99fef.png)

Should we add a `z-index of 10` to the green box as well, to let it slide behind the search ?

**Comment by jackmcdade** [comment]
Fixed.
