### ISSUE TITLE
installation.md – instructions for running multiple instances

### ISSUE THREAD

**Issue by websmyth** [statamic/docs#199]
Following up on @jasonvarga’s 💡  Discord instructions...whenever an _existing_ site is pulled down/installed, the user needs to:

1. Run `composer install`
2. Create the `.env` file
3. Run `php artisan key:generate`

These were things I didn’t know I needed to know, and I wondered why setting up new instances of a site was a pain. Reckon this is worth including somewhere on this page.

**Comment by damcclean** [comment]
I think this is a duplicate of #197

**Comment by websmyth** [comment]
Ah, I wondered if Jason might have created an issue but didn’t see this. Good spot. 👍

**Comment by damcclean** [comment]
I'm closing this as it's a duplicate.
