### ISSUE TITLE
Add examples for Query Scopes & Filters

### ISSUE THREAD

**Issue by edalzell** [statamic/docs#2]
In the `Query Scopes` section, you mention:

> You may create scopes that can be used in various places, such as inside the collection tag or inside control panel listings.

Would be great if there were examples (or links to examples) of how those can actually be used.

**Comment by JonKaric** [comment]
@edalzell Is this still an isssue? Looks like there's been quite a changes since

**Comment by jasonvarga** [comment]
Thanks for the ping. There's links to stuff now.
