### ISSUE TITLE
Document widgets

### ISSUE THREAD

**Issue by jasonvarga** [statamic/docs#205]

**Comment by jesseleite** [comment]
How's this?

![image](https://user-images.githubusercontent.com/5187394/92164760-dc815f00-ee03-11ea-8b03-93388ee99c80.png)

**Comment by jackmcdade** [comment]
Love it so much.

**Comment by jasonvarga** [comment]
![image](https://user-images.githubusercontent.com/105211/92175572-d3e05700-ee0a-11ea-8556-1ee7862c6222.gif)

**Comment by jesseleite** [comment]
![image](https://user-images.githubusercontent.com/5187394/92175709-21f55a80-ee0b-11ea-9032-363ceafcbcef.png)

**Comment by jonassiewertsen** [comment]
Can this be closed @jasonvarga ?

The widgets have been documented (but without image)
https://statamic.dev/widgets#content

**Comment by jasonvarga** [comment]
Yup thanks for the ping.
