### ISSUE TITLE
Add entries fieldtype to docs.

### ISSUE THREAD

**Issue by twd3** [statamic/docs#224]
Add entries fieldtype to docs. People are confused how to relate entries because relate still there and entries not there.

**Comment by cherrykoda** [comment]
seconded - trying to find "entries" in the fieldtypes within docs and it's not listed at all (lloking for reference on how to call in templates)

**Comment by duncanmcclean** [comment]
Looks like the entries fieldtype now has some documentation https://statamic.dev/fieldtypes/entries#content
