### ISSUE TITLE
Error 404 on https://statamic.dev/static-caching

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/docs#226]
I am getting an error 404 on https://statamic.dev/static-caching. The page loads fine though. Just a header thing it seems.

**Comment by jackmcdade** [comment]
That's so weird! 🤔

**Comment by AndreasSchantl** [comment]
Cool cool. What's been the matter?

**Comment by jasonvarga** [comment]
An nginx rule was getting in the way.
