### ISSUE TITLE
Document the deployment process

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/docs#238]
I've seen it many times where someone has tried and struggled to get Statamic deployed to a server. I think it would be a good idea for a knowledge base article that covers deployment for:

* Laravel Forge (recommended)
* Shared hosting - FTP up and down, although could be a good idea to reiterate that shared hosting servers will need to have Composer installed (commonly they don't)
* Non-managed VPS - where you can git pull the changes down

**Comment by jackmcdade** [comment]
Done. https://statamic.dev/deploying
