### ISSUE TITLE
need information on adding custom widget to CP dashboard

### ISSUE THREAD

**Issue by aadind** [statamic/docs#264]
https://statamic.dev/extending/widgets

This page is empty and i urgently need info on creating our own widget using a template or partial.

**Comment by jasonvarga** [comment]
It's the same as in v2 https://v2.statamic.com/widgets except instead of writing yaml into cp.yaml, you write a php array into config/statamic/cp.php

If you want to write a simple template, use the `template` widget that just points to a view.

**Comment by jasonvarga** [comment]
Closing in favor of #205

**Comment by aadind** [comment]
thank you! It works perfectly.
