### ISSUE TITLE
Missing Email Templating Documentation/Knowledge Base

### ISSUE THREAD

**Issue by kevnk** [statamic/docs#268]
The "Learn how to create your emails" link on [the Forms page](https://statamic.dev/forms) links to a 404 page: https://statamic.dev/knowledge-base/emails

**Comment by damcclean** [comment]
Does the [email section](https://statamic.dev/forms#emails) of that same page not contain information that you're looking for?

**Comment by kevnk** [comment]
I honestly cannot remember what I was originally looking for.... I think I was looking for what templates I needed to add in order to have custom emails.

**Comment by JonKaric** [comment]
Is this what you were looking for?

https://statamic.dev/email#customizing

**Comment by kevnk** [comment]
That seems to be right and seems like it's fixed now
