### ISSUE TITLE
Show replacements for removed conditions

### ISSUE THREAD

**Issue by edalzell** [statamic/docs#3]
In the `Tag Conditions` section of the [upgrade guide](https://statamic.dev/upgrade-guide), it is mentioned that several conditions have been removed.

Would be nice to see what the replacements are for `contains` not working in an array, for example.

**Comment by jackmcdade** [comment]
Unfortunately there is no replacement for contains/doesnt_contain on arrays. We're conforming to the query builder spec and it needs to be db/driver compatible. 

We'll look at ways of supporting it for the stache driver though, but as far as showing replacements (the topic of this issue), we're all up to date in the docs.
