### ISSUE TITLE
Glide presets need docs

### ISSUE THREAD

**Issue by johncarter-** [statamic/docs#300]
The https://statamic.dev/tags/glide page needs mention that it also accepts `preset='custom-preset-name'` as a param.

`{{ glide src='an-image-url' preset='custom-preset-name' }}`

**Comment by sjclark** [comment]
@johncarter- can you give me a super quick example of how the presets actually work? Seem to be going in circles with getting it to work correctly?

**Comment by johncarter-** [comment]
I am not actually sure, I ended up using responsive images by Spatie because I wanted to use Blade templates.

**Comment by jasonvarga** [comment]
I just discovered this after I tried to point someone to the preset docs and to my surprise it didn't exist.

The short version, look at the config here:
https://github.com/statamic/statamic/blob/d1cc13bc04956f4095a4ebaa5220d1f3b873483f/config/statamic/assets.php#L58-L71

If you do `{{ glide:myimage preset="small" }}` it would be the equivalent of doing `{{ glide:myimage w="200" h="200" q="75" fit="crop" }}`. Plus, when you upload an asset, it'll pre-generate that size so its fast when you actually try to use it.
