### ISSUE TITLE
{{ redirect }} Tag param: 302 is a temporary redirect

### ISSUE THREAD

**Issue by johncarter-** [statamic/docs#301]
https://statamic.dev/tags/redirect#content

On the `response` parameter there is an error.

![image](https://user-images.githubusercontent.com/3776888/98010656-d94c2480-1dee-11eb-974d-14d74f8a18d7.png)

302 redirect is **temporary** not permanent.

Would PR, but not sure if it defaults to 301 or 302.

**Comment by jasonvarga** [comment]
Fixed, thanks! (It defaults to 302)
