### ISSUE TITLE
Link fieldtype is missing

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/docs#316]
What's possible with this one? Anything magic?

**Comment by j3ll3yfi5h** [comment]
How can I show a linktext field dependent on the link toggle?

**Comment by jonassiewertsen** [comment]
Good catch. The link filedtype is missing right now in the docs. 

I would suggest to ask on Discord for specific questions, the community is really helpful, willing to help and much faster than here on GitHub.

**Comment by janparkio** [comment]
I believe [FieldTYPES] (https://statamic.dev/fieldtypes) is this one.

The one missing is [FieldSETS](https://statamic.dev/fieldsets)
![Screen Shot 2020-12-03 at 18 36 11](https://user-images.githubusercontent.com/9617583/101091109-776e0e80-3596-11eb-802d-e60fe43b3b8a.png)

Seems like multiple people myself included #296 mentioned these issues and in my case, they just closed the issue.

**Comment by j3ll3yfi5h** [comment]
@janparkio nothing to do with this issue

**Comment by janparkio** [comment]
@j3ll3yfi5h ok, my bad. I'll remove my comment.

**Comment by j3ll3yfi5h** [comment]
@janparkio
The **link** fieldtype is not explained in docs:
![Bildschirmfoto 2020-12-04 um 13 57 48](https://user-images.githubusercontent.com/6337411/101166553-c0769f00-3638-11eb-9273-587de09ebd50.jpg)

**Comment by janparkio** [comment]
@j3ll3yfi5h Gotcha! You're certainly right.

**Comment by espenlg** [comment]
Would love to see this in the documentation 👍
