### ISSUE TITLE
Hosts

### ISSUE THREAD

**Issue by jasonvarga** [statamic/docs#325]
Should we add a section that shows which hosts play nice with Statamic?

Basically I would love to get rid of https://github.com/statamic/hosts which is just another repo to stay on top of.
Also I'm pretty sure we don't link to that repo anywhere (anymore?)

**Comment by robdekort** [comment]
I think just specifying the requirements is enough, maybe together with a: "At Statamic we love Digital Ocean together with Laravel Forge".

**Comment by JonKaric** [comment]
I think it's a good idea. I don't agree with removing it entirely though, having the section may encourage hosts to better accommodate Statamic. Eg. Siteground has a fixed memory limit, making it impossible to update via the command line.

**Comment by jasonvarga** [comment]
Yeah, no intention of removing it.

**Comment by sjclark** [comment]
> I think just specifying the requirements is enough, maybe together with a: "At Statamic we love Digital Ocean together with Laravel Forge".
@robdekort 

![Screen Shot 2021-04-28 at 5 09 00 pm](https://user-images.githubusercontent.com/4531017/116361572-763ec600-a844-11eb-9f8a-25f5c1470b89.png)

**Comment by jackmcdade** [comment]
Our recommended hosts have a place in the install section — i think that's good enough for now.
