### ISSUE TITLE
Update Scripts is a ghost town...

### ISSUE THREAD

**Issue by skylennard** [statamic/docs#419]
Partygoer: `This door wasn't locked and there's just an empty room on the other side.`

https://statamic.dev/extending/update-scripts

**Comment by jasonvarga** [comment]
Where'd it link from?

**Comment by jackmcdade** [comment]
The blog post. Whoops.

**Comment by jasonvarga** [comment]
It's over here: https://statamic.dev/extending/addons#update-scripts
