### ISSUE TITLE
Extending Upgrade 3.0 to 3.1

### ISSUE THREAD

**Issue by felixstoessel** [statamic/docs#429]
It would be great to add a reference in the upgrade guide to following link:
https://github.com/statamic/statamic/compare/3.0...3.1?diff=split

With this, I found lots of missing configs I had to manually update because I created my project a while back via `statamic/statamic`.

**Comment by duncanmcclean** [comment]
Unfortunately, as it's a GitHub comparison page, there's not really a way we can add any 'notes' or 'comments' so I'm going to close this issue.

Also, technically your project will work without the new configs being in place, they will fallback to the Statamic defaults.

If you have any other ideas though, feel free to add them here.
