### ISSUE TITLE
Create users by hand

### ISSUE THREAD

**Issue by kofyebs** [statamic/docs#431]
On the documentation page `https://statamic.dev/knowledge-base/creating-user-files` the page doesn't exist.

**Comment by jackmcdade** [comment]
Where is that linked from? The URL is https://statamic.dev/knowledge-base/creating-users-by-hand

**Comment by kofyebs** [comment]
> Where is that linked from? The URL is https://statamic.dev/knowledge-base/creating-users-by-hand
> […](#)
> On Apr 4, 2021, at 5:01 AM, kofyebs ***@***.***> wrote: ﻿ On the documentation page https://statamic.dev/knowledge-base/creating-user-files the page doesn't exist. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

from this page [https://statamic.dev/users#user-fields](url)

**Comment by kofyebs** [comment]
from this page [https://statamic.dev/users#user-fields](url)
