### ISSUE TITLE
Broken links / Missing docs

### ISSUE THREAD

**Issue by JonKaric** [statamic/docs#443]
These are a few links that are broken or have missing docs.

`this is the text of the link`

- [x] ~~https://statamic.dev/blueprints `content modeling` (this has been hotfixed in one of my PR's)~~ **Fixed**
- [x] ~~https://statamic.dev/structures#templating `structure tag` (The same as #375)~~
- [x] ~~https://statamic.dev/graphql#global-set-interface `Blueprint is Optional`~~
- [ ] https://statamic.dev/protecting-content#password ` protect:password_form`
- [ ] https://statamic.dev/conditions#overview `users`

**Comment by Konafets** [comment]
The users link is fixed (last topic).

I also created an dedicated issue for the second last topic https://github.com/statamic/docs/issues/647

**Comment by jackmcdade** [comment]
Nice one – we'll be able to close this issue now. Thanks!
