### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by merijnponzo** [statamic/docs#462]
Hi there, 
Some possible improvements to the statamic.com website for the main nav

- [x] add github repo link (as icon) at the homepage statamic.com (top right in nav)
- [x] add documenation as a main nav item instead of within subnav resources as 'docs'
- [x] rename resources to 'community' 
- [x] move 'pricing' out of the  product nav as a seperate nav item 'pricing'
- [x] add 'features' to product as a new page with all of the best features listed

The new nav structure becomes

- product (subnav)
- pricing (landing)
- resources (subnav)
- marketplace (subnav)
- community (subnav)
- docs (documentation)

within the docs 

- [x] Add a chapter like 'Getting Started'  but then as 'Guides'
- [ ] Create guides for common used cases which can be used as kinda 'quickscan' overviews of the documentation

A guide could be for example
- Create a blog with statamic & innertiajs

This guide handles all of the logic which is needed if a developer needs to create custom web routes and controllers with examples for getting blog entries or dispplay a single blog entry

;-)
[https://statamic.com/forum/5393-get-all-template-content-into-inertia](url)

great cms!

**Comment by jackmcdade** [comment]
Thanks for the ideas! A few of these have been on my todo list for a while, I'd expect you'd see most of these changes sooner or later :)
