### ISSUE TITLE
collection:next and collection:previous -> only with built-in date field?

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/docs#465]
> Ah, you'll need to use the built-in date field if you want to use collection:next.
(https://discord.com/channels/489818810157891584/489819906540568593/791268796056338465)

Does this only work with the default date field as @duncanmcclean mentioned in December?

https://statamic.dev/tags/collection-next
https://statamic.dev/tags/collection-previous

**Comment by jackmcdade** [comment]
That is correct. It's now documented. Thanks!
