### ISSUE TITLE
Upgrade Statamic in Docs?

### ISSUE THREAD

**Issue by edalzell** [statamic/docs#476]
Currently it's Laravel 6 and php 7.4, are you open to an upgrade?

Folks are having a challenge PR'ing things sometimes:
<img width="822" alt="CleanShot 2021-05-23 at 11 20 14@2x" src="https://user-images.githubusercontent.com/6069653/119272063-1a542c80-bbb9-11eb-9b4a-0c57e19ff43c.png">

I'd sponsor a Laravel shift, if that makes things easier for ya.

**Comment by jackmcdade** [comment]
I have free shifts for life, that’s not the issue. There are certain areas of the site that rely on older, beta features. Gotta take time to manually fix everything. It’s about time tho. No worries.

**Comment by edalzell** [comment]
> I have free shifts for life, that’s not the issue. There are certain areas of the site that rely on older, beta features. Gotta take time to manually fix everything. It’s about time tho. No worries.
> […](#)

Looks like Simon is starting it: https://github.com/simonhamp/statamic-docs/tree/upgrade-to-L8
