### ISSUE TITLE
Please add a document which shows how to add Composer’s system-wide vendor bin directory to $PATH

### ISSUE THREAD

**Issue by sebastianbachmann** [statamic/docs#492]
Hi,

can you please add this Page? Currently the _[Here's how](https://statamic.dev/knowledge-base/adding-to-path)_ link on this website shows a _Nothing to see here message_ 😊

Thanks!

**Comment by jasonvarga** [comment]
We had a page already, but it was renamed and the link wasn't updated, sorry!

Here it is: https://statamic.dev/knowledge-base/command-not-found-statamic

**Comment by sebastianbachmann** [comment]
Thank you!
