### ISSUE TITLE
Recently updated list is a bit broken

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/docs#511]
I know for a fact there wasn't an update 4 minutes ago by looking at the Git commits.

![image](https://user-images.githubusercontent.com/19637309/126452743-9741808b-b767-41e8-ae6c-158181afb383.png)

![image](https://user-images.githubusercontent.com/19637309/126454857-1fdb3266-fa39-4e94-8a80-fa0ad395b096.png)

**Comment by jackmcdade** [comment]
Ah yeah that's because we're using `STATIC_CACHING=full`. I could make it just relative to the day (e.g. "today", "yesterday", etc) and have a daily cache pop task. Whatcha think?

**Comment by duncanmcclean** [comment]
Yeah, that's probably a good idea. 

Also, not quite sure what's happening with the top two in the list.

**Comment by duncanmcclean** [comment]
Noticed another irk with using static caching, the XML header isn't being applied to https://statamic.dev/sitemap.xml properly. Not sure if it's possible to fix, if it is probably an Nginx change.

Anyways, that's a really tiny thing. 😅

**Comment by jackmcdade** [comment]
Excluded it from the cache and it's all good now. Nice catch @duncanmcclean!
