### ISSUE TITLE
Add a page for Commands

### ISSUE THREAD

**Issue by dougstjohn** [statamic/docs#52]
Similar to https://docs.statamic.com/addons/classes/commands

**Comment by jonassiewertsen** [comment]
Is this what you are looking for @dougstjohn ?
https://statamic.dev/cli#commands

There is a dedicated commands page with a link a the bottom, for additional reading on the Laravel docs where you can find good examples on how to create your own commands. 

The Statamic addon docs do give a hint on how to register your own commands:
https://statamic.dev/extending/addons#registering-components

Does this feel good to you or are you missing some information to make it even more clear?

**Comment by dougstjohn** [comment]
I can't remember what was on the v2 docs, but I think it had an example Command class to reference.

It'd be nice to be able to do 'php please make:command' to generate a custom command into the Statamic project or Statamic addon. Then extra docs wouldn't be needed since it'd be easy to generate commands just like fieldtypes, widgets, etc.

**Comment by damcclean** [comment]
Laravel actually provides this for you.

You can run:

php artisan make:command (CommandName)

**Comment by jonassiewertsen** [comment]
@dougstjohn @damcclean 
What would you think about a section on the statamic command page, saying something like "Useful Laravel Commands". 

That could make clear in the docs how to create custom commands. 
I could create a PR if both of you think it's useful.

**Comment by jonassiewertsen** [comment]
There has been no feedback, so I will close it for now.
