### ISSUE TITLE
Quick Start should better explain what's meant by "local dev environment"

### ISSUE THREAD

**Issue by grovberg** [statamic/docs#541]
The overview for the QS guide implies that installing composer will create a functional dev environment, but the quick start instructions will not work without additional steps (like installing Valet for example).

An easy fix for this would be to link the phrase "local dev environment" in the overview to https://statamic.dev/requirements#development-environments

Even better would be one location that listed out everything a new user will need to install before installing Statamic.

**Comment by jackmcdade** [comment]
We're in the process of writing a local dev environment how-to guide that will be linked from this page. We knew it was coming, which is why it's a bit light right now.
