### ISSUE TITLE
Building Modifiers: Variable as param doesn't work using shorthand style

### ISSUE THREAD

**Issue by sebszocinski** [statamic/docs#546]
https://statamic.dev/extending/modifiers

This example using a variable and shorthand mode no longer works as of Statamic v3.2.9:
```
times: 5
thing: Pizza

{{ thing | repeat:times }}
```

You need to use this syntax:
```
{{ thing repeat="{times}" }}
```

**Comment by jesseleite** [comment]
Hmm, that's odd. I'm able to do either of these fine in 3.2.9...

```html
{{ thing | repeat:times }}
{{ thing :repeat="times" }}
```

But not this for some reason...

```html
{{ thing repeat="{times}" }}
```

🤔

**Comment by jasonvarga** [comment]
Works fine here too.

Please feel free to open an issue on statamic/cms with a way to reproduce it.
