### ISSUE TITLE
Document the `{{ users }}` tag

### ISSUE THREAD

**Issue by jacksleight** [statamic/docs#624]
There's a `{{ users }}` tag that allows you to fetch/filter/sort/paginate a list of users, just like the collection tag, but it's not documented.

I tried to write something (using the collection tag as a starter) but I'm not exactly sure which parameters and variables are supported or how best to explain it without duplicating a load of content from the collection tag docs.

**Comment by jackmcdade** [comment]
Nice catch, thanks!
