### ISSUE TITLE
 Collection Tag Filtering Taxonomies does not refer to using variables for filtering

### ISSUE THREAD

**Issue by timgreenwood** [statamic/docs#625]
The example shown in [Collection Tag Filtering Taxonomies](https://statamic.dev/tags/collection#taxonomies) only refers to filtering by a literal string and I was not able to find an example of doing the same using a variable.

**Comment by jackmcdade** [comment]
That's documented in the Antlers section – it's a template language level feature: https://statamic.dev/antlers#variables-inside-tag-parameters

**Comment by timgreenwood** [comment]
> That's documented in the Antlers section – it's a template language level feature: https://statamic.dev/antlers#variables-inside-tag-parameters

Sorry Jack, I completely missed it there!

**Comment by jackmcdade** [comment]
No worries!
