### ISSUE TITLE
Search returns a 404 error

### ISSUE THREAD

**Issue by damcclean** [statamic/docs#63]
When visiting a search results page (like here https://statamic.dev/search-results?q=asset), a 404 page is returned.

**Comment by jackmcdade** [comment]
Interesting. We also have...

![image](https://user-images.githubusercontent.com/44739/74368895-77e8af00-4da2-11ea-9411-bb2f37257bf2.png)

**Comment by damcclean** [comment]
Yeah, I saw that one too, don't think it's meant to be there.
