### ISSUE TITLE
The link to "Github Discussions" is broken

### ISSUE THREAD

**Issue by Konafets** [statamic/docs#661]
On the [Quickstart guide](https://statamic.dev/quick-start-guide), there is a link to the Github discussions, which returns a 404 page. If someone tells me where to link, I will create a PR for this issue.

https://github.com/statamic/discussions

![2021-12-28_14-02-51](https://user-images.githubusercontent.com/363363/147569013-7a3f5238-3efa-4ee7-a6ba-2a594219a659.jpg)

**Comment by duncanmcclean** [comment]
The correct URL is https://github.com/statamic/cms/discussions
