### ISSUE TITLE
Quick start guide refers to old Scaffold Resources

### ISSUE THREAD

**Issue by Konafets** [statamic/docs#662]
In recent versions this option is called "Scaffold Views".

- [ ] Update the text
- [ ] Update the screenshot

**Old**

![2021-12-28_14-14-49](https://user-images.githubusercontent.com/363363/147570131-1a9bc7d5-da4d-40a0-8ec4-851a091a4c4e.jpg)

**New**
![2021-12-28_14-12-11](https://user-images.githubusercontent.com/363363/147570064-0e2cb7c2-d90a-4368-aa3d-4894f3cd364f.jpg)

**Comment by jackmcdade** [comment]
Fixed in 88e77b3.
