### ISSUE TITLE
`->where('folder', 'team_photos')` seems not to work

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/docs#676]
https://github.com/statamic/docs/blob/c6ca372026d5c437508e1865507f356f164bc0ff/content/collections/repositories/asset-repository.md?plain=1#L52

Worked for me like this instead:
`->where('folder', 'like', '%team_photos%')`

Also mentioned here:
https://discord.com/channels/489818810157891584/489819906540568593/738400493251985429

**Comment by jasonvarga** [comment]
It seems to work fine. It is expecting the the full path of the folder (from the root of the container)

If you have `/container/team_photos`, then `->where('folder', 'team_photos')` will work.

If you have `/container/foo/bar/team_photos`, then `->where('folder', 'team_photos')` will *not* work.
You need to do `->where('folder', 'foo/bar/team_photos')`

**Comment by j3ll3yfi5h** [comment]
Hm, that is interesting...

Maybe it was the combination of `folder` and `filename`?

My query looked like this:
```
Asset::query()
->where('container', 'assets')
->where('folder/subfolder')
->where('filename', 'filename.jpg')
->get()
```

**Comment by jasonvarga** [comment]
The `filename` does not have an extension. `basename` does.

`->where('basename', 'filename.jpg')`

**Comment by j3ll3yfi5h** [comment]
Ah, that was it! Thank you very much for explanations!
