### ISSUE TITLE
Add 301 Redirect to 3.1 to 3.2 upgrade guide - referenced in changelog

### ISSUE THREAD

**Issue by jsblair9** [statamic/docs#683]
Currently the changelog at 3.2 references this link `https://statamic.dev/upgrade-guide-3-1-to-3-2` and looks like that has moved here: `https://statamic.dev/upgrade-guide/3-1-to-3-2`

![CleanShot 2022-01-11 at 09 38 42@2x](https://user-images.githubusercontent.com/4450975/148973548-f8f796a1-93f9-49de-a816-c1a330bfec74.jpg)

**Comment by jasonvarga** [comment]
We'll update the link in the changelog itself. Thanks!
