### ISSUE TITLE
How to cast the $entry to something custom?

### ISSUE THREAD

**Issue by ceesvanegmond** [statamic/docs#684]
Hi all,

In the documentation the're a section about augmentation. https://statamic.dev/extending/augmentation#augmentable
In these docs you are talking about a `Product` entry. However what I'm missing is how to convert an `Entry` to this custom `Product`. For instance, when I have a `News` item I would query using the `EntityRepository` but would like to receive a `News` object instead of a generic `Entry`. 

Is this possible? Do I miss something in the docs?
I'm submitting this the the `docs` repo beause I would like to improve the docs.

**Comment by jackmcdade** [comment]
What would the difference be between a `News` object and a generic `Entry`?

**Comment by ceesvanegmond** [comment]
What about the fields? News could have a field called *highlight_on_home* for ezample. Also methods like *getRelatedNews*

**Comment by jackmcdade** [comment]
The fields are there, as part of the `Entry` object. https://statamic.dev/extending/data#getting-field-data

What would `getRelatedNews()` do, and how would that happen automatically?

**Comment by jackmcdade** [comment]
Closing as I think this is just a misunderstanding when you see an `Entry` object but are unsure of how to interact with it. Feel free to commend and continue the discussion, or take it to https://github.com/statamic/cms/discussions.
