### ISSUE TITLE
Closing the search modal jumps the page

### ISSUE THREAD

**Issue by mynetx** [statamic/docs#707]
When clicking the Search box in the header and then closing it (using <kbd>Esc</kbd> or clicking into the backdrop), the scroll position will jump down unexpectedly.

![CleanShot 2022-01-26 at 10 32 58](https://user-images.githubusercontent.com/6348321/151138472-392f85e0-afa1-46b8-884f-fbd02d1ade25.gif)

**Comment by jackmcdade** [comment]
This is apparently a known issue with Algolia DocSearch and they don't have a fix yet. I tried all the workarounds other people suggested but they didn't work on our site. 😞 

https://github.com/algolia/docsearch/issues/1260

**Comment by jackmcdade** [comment]
Actually, made one of them work. It's dumb but whatever.

**Comment by sjclark** [comment]
> Actually, made one of them work. It's dumb but whatever.

Looks like the temp fix is a little wonky: https://github.com/statamic/docs/commit/aeed3be07be42396d89c75007368fe4a3d0297ec#commitcomment-81484612
😂
