### ISSUE TITLE
Broken layout for navbar and buttons on `md:` breakpoint

### ISSUE THREAD

**Issue by adevade** [statamic/docs#719]
https://statamic.dev/reference

![image](https://user-images.githubusercontent.com/1066486/151571441-66e21cab-3bf4-4f2f-bb1e-1ee67462fb24.png)

---

@jackmcdade 

P.S. I hope it doesn't come across as something negative that I'm creating many issues. It's just some things I've noticed while using the docs the last week.

I've recently started using Statamic for a site at work, and love it so far! Currently converting from a 10 year old WordPress install. I'll start making PRs instead of issues as soon as I can! ❤️

**Comment by jackmcdade** [comment]
Looks good to me! 🤣
