### ISSUE TITLE
Tips & Tricks: I want to increase file upload size

### ISSUE THREAD

**Issue by jmalko** [statamic/docs#727]
Having trouble uploading files larger than 4mb?  You need to configure PHP and potentially your server to allow for that.  I am increasing my maximum upload filesize to 100mb.

My example server is running Ubuntu 20.04 LTS, Nginx, and PHP-FPM 8.0.

## PHP Configuration

1. Find your active php.ini file.  The path is `/etc/php/8.0/fpm/php.ini` in this example server.
2. Make adjustments to your php.ini file:
```
post_max_size 100M;
upload_max_filesize 100M;
```
3. Save the file and reload php-fpm to put the new configuration into effect.  In the example server, run `sudo service php8.0-fpm reload`.
4. Test your work.

## NGINX Configuration

A server-wide configuration must be made in order to allow NGINX to accept larger uploads.
In the example server, this configuration is located in `/etc/nginx/nginx.conf`.

Add the following line to your http { } configuration block:
```
http {
    #
    client_max_body_size 100m;
    #
}
```
Verify your configuration by running `sudo nginx -t`.  If all is good, you must reload Nginx in order to see the changes.  Run `sudo service nginx reload`, then check your work by uploading a file.

**Comment by jmalko** [comment]
Am making a PR with more complete info.

**Comment by jackmcdade** [comment]
Will wait for that PR – it's a bit super specific to a single environment, but we'd merge it in :)
