### ISSUE TITLE
Legacy NPM run error

### ISSUE THREAD

**Issue by jmalko** [statamic/docs#728]
`error:03000086:digital envelope routines::initialization error` when trying to run `npm run dev`.

A temporary solution is to run `export NODE_OPTIONS=--openssl-legacy-provider` and then re-run `npm run dev`.

Not related to Statamic per se, but since we depend on this build chain, it is worth mentioning somewhere here vs. rummaging through StackOverflow.

**Comment by Konafets** [comment]
How does it relate with the documentation repository? Got no error when I run `npm run dev`.

**Comment by jackmcdade** [comment]
I think just the mention if it in an issue could be enough for some Google Fu. I'll close this because there's not really anything we can do about that :)

**Comment by jmalko** [comment]
Sounds good.

@Konafets you'll see this if you're using NodeJS v17+.  v16 and below, no problemo.
