### ISSUE TITLE
Textile modifier is documented, but has been removed

### ISSUE THREAD

**Issue by Christophvh** [statamic/docs#755]
Textile modifier is documented here: https://statamic.dev/modifiers/textile

But when trying to use textile I get an error. I think the textile modifier has been removed.

**Comment by duncanmcclean** [comment]
Good spot! For ref: this is the commit where it was removed [statamic/cms-1baeae8](https://github.com/statamic/cms/commit/1baeae80c738e20dc0911b3ca112ae39aa5cee32).

**Comment by jackmcdade** [comment]
Thanks!
