### ISSUE TITLE
Lack of documentation to add a site to an existing multi-site install

### ISSUE THREAD

**Issue by sjclark** [statamic/docs#778]
Minimal documentation on how to add a site to an existing multisite - particularly if the multi-site was initially setup with the multisite command it can be hard to figure out.

**Consider adding an "Add a Site" section to [https://statamic.dev/multi-site](https://statamic.dev/multi-site)**

The only helpful existing documentation is a bit hidden away in the Tips section (https://statamic.dev/tips/converting-from-single-to-multi-site), and is really more focused on conversion rather than adding to. Or the "Rename a site" section on the multi-site page could potentially point you in the right direction but also isn't explicit.

RE: https://discordapp.com/channels/489818810157891584/489819906540568593/959695581452853248

**Comment by jasonvarga** [comment]
I guess the snippets of the configuration file with multiple sites in it isn't enough. Can do.

**Comment by jackmcdade** [comment]
Added in 1050f0e2cf490c6f048ca3de2621a6bd4b3b0de6
