### ISSUE TITLE
Structure tag missing

### ISSUE THREAD

**Issue by zuzana-kunckova** [statamic/docs#78]
There is a link on the Structures page (https://statamic.dev/structures) to the `structure tag`, however, when you click on the link, a 'Page not found' text is displayed. There is no `structure` tag right now.

![Screenshot 2020-02-25 at 10 36 37](https://user-images.githubusercontent.com/15965102/75239569-d5292b00-57ba-11ea-8d9c-504ef580ec7e.png)

**Comment by damcclean** [comment]
This might be because structures are actually getting rebuilt right now so it's not worth them writing docs before it's finalised.

But I think it's almost nearly done....

**Comment by jesseleite** [comment]
> "Almost nearly" accounts for the range between 7% and 92%.

_Source_: Stats Canada, 2011
