### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Pin0** [statamic/docs#794]
Following this:

https://statamic.dev/installing/docker#installing-laravel -> here it tells you to simplify the docker-compose.yml and remove some of the docker images amongst others the mysql image.

And then this:

https://statamic.dev/installing/laravel#install-statamic

Gives me:

```
@php artisan statamic:search:update --all --ansi

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: Name or service not known (SQL: select * from `users`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:745
    741▕         // If an exception occurs when attempting to run a query, we'll format the error
    742▕         // message to include the bindings with SQL, which will make this exception a
    743▕         // lot more helpful to the developer instead of just the database's errors.
    744▕         catch (Exception $e) {
  ➜ 745▕             throw new QueryException(
    746▕                 $query, $this->prepareBindings($bindings), $e
    747▕             );
    748▕         }
    749▕     }

      +40 vendor frames
  41  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan statamic:search:update --all --ansi handling the post-autoload-dump event returned with error code 1
```

It's probably some Laravel issue but if I continue the same error appears if I visit localhost/cp or if I create a user using

`./vendor/bin/sail php please make:user
`
I can create a user if I change repository to file in config/statamic/users.php. But changing that does not get rid of the error in localhost/cp

Tried it twice now both with the same issue... any suggestions would be appreciated

**Comment by chokeul8r** [comment]
@Pin0 did you ever find a solution to this problem? I am having the same issue. It seems that more extensive documentation need to developed because installing Statamic into a existing Laravel 9 application via Docker/Sail is beyond the scope of the current documentation.

**Comment by Pin0** [comment]
@chokeul8r I eventually got it to work. It had something to do with lack of resources available to docker. I added more memory and cleaned up old docker images.
So this issue can be closed.
