### ISSUE TITLE
Change example of bard set partials to new antlers format

### ISSUE THREAD

**Issue by twd3** [statamic/docs#8]
On this page: https://statamic.dev/fieldtypes/bard#templating

You should change the example that reads
```
partials/
|-- sets/
|   |-- gallery.html
|   |-- image.html
|   |-- poll.html
|   |-- text.html
|   |-- video.html
```
To:
```
resources/views/partials/
|-- sets/
|   |-- gallery.antlers.html
|   |-- image.antlers.html
|   |-- poll.antlers.html
|   |-- text.antlers.html
|   |-- video.antlers.html
```
This way people know where to put these partials and they'll be reminded of the new antlers naming for them.

**Comment by jonassiewertsen** [comment]
This PR updates the tiptap links:
https://github.com/statamic/docs/pull/240
