### ISSUE TITLE
`relate:` tag, not available anymore?

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/docs#812]
Just came across the relate tag. I think it is not available anymore?

https://github.com/statamic/docs/blame/master/content/collections/fieldtypes/terms.md#L86

**Comment by joshuablum** [comment]
Hey @j3ll3yfi5h,

Thanks for point that out!
It's still available ([see code here](https://github.com/statamic/cms/blob/3.3/src/Tags/Relate.php)) but the docs for it are missing. Will fix that 🚀
