### ISSUE TITLE
`is_array` modifier is missing

### ISSUE THREAD

**Issue by wm-simon** [statamic/docs#820]
I've tested `is_array` and it's working, but I can not find the modifier in the docs.

**Comment by joshuablum** [comment]
It seems a little confusing, so I guess you're both right, sorry.
Probably better to document it 💯

But like you said, @duncanmcclean, [it's](https://github.com/statamic/cms/blob/3.3/src/Modifiers/CoreModifiers.php#L1007) just a wrapper around PHP's function.
```php
public function isArray($value)
{
    return is_array($value);
}
```

**Comment by joshuablum** [comment]
https://github.com/statamic/docs/pull/826
