### ISSUE TITLE
Document reccomended Local Developer Tools within Local Developer Install page

### ISSUE THREAD

**Issue by sjclark** [statamic/docs#860]
Had a user in the discord who had followed the Local Statamic Install instructions on a Mac but couldn't get the site to work. When asked if they had setup valet correctly they responded "Whats Valet"?

Made me realise the local install page actually has no reference to any sort of local developer setup, despite even giving example urls such as `http://$project_name.test`

https://statamic.dev/installing/local

Think it would make sense for the **Local Install** page to ideally also reference the recommended local tools; as per https://statamic.dev/requirements#development-environments

Guess it's blurred lines between the two pages a bit though!

**Comment by sjclark** [comment]
Just had this again today in the Peak discord
<img width="542" alt="Screen Shot 2022-07-12 at 5 25 18 pm" src="https://user-images.githubusercontent.com/4531017/178433180-8171fe94-089f-40d4-927c-ba0adde7286f.png">

<img width="501" alt="Screen Shot 2022-07-12 at 5 25 01 pm" src="https://user-images.githubusercontent.com/4531017/178433198-0e40ac98-5dc3-4a0c-8517-7c39a2b34082.png">

**Comment by duncanmcclean** [comment]
There's one or two people a week I see that run into this issue on GitHub/Discord too.

**Comment by sjclark** [comment]
Probably also worth closing https://github.com/statamic/docs/issues/566
