### ISSUE TITLE
Code Fields not beeing displayed correctly

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/docs#874]
Some code fields do not have the correct formatting: 

https://statamic.dev/upgrade-guide/3-1-to-3-2

**Comment by jasonvarga** [comment]
What's the problem?

**Comment by jonassiewertsen** [comment]
The code highlighting is missing. 

![Bildschirmfoto 2022-07-18 um 16 35 25](https://user-images.githubusercontent.com/38906163/179535415-33f2806d-41b2-418c-9e8d-abaa011017f1.png)

**Comment by Konafets** [comment]
This happens very regularly and works some time later again. Torchlight, the service which is used for syntax highlighting has some hiccups.

**Comment by jasonvarga** [comment]
I thought you meant something about the `code` fieldtype broke during the upgrade to 3.2 😂
