### ISSUE TITLE
When trying to delete / detach a multi-site entry, the CP links to a dead page in the docs.

### ISSUE THREAD

**Issue by tao** [statamic/docs#891]
![Screenshot 2022-08-05 at 23 31 03](https://user-images.githubusercontent.com/1446331/183209331-5f50849c-615f-4fe7-acce-6df2175b7e3a.png)
 
It links here to read more: https://statamic.dev/knowledge-base/localizing-entries#deleting
 
 But that link is no longer correct.

**Comment by duncanmcclean** [comment]
Found where it should go: https://statamic.dev/tips/localizing-entries#deleting
