### ISSUE TITLE
Inconsistent references to 40+ (42? 38? 41? Nearly 40?) Fieldtypes

### ISSUE THREAD

**Issue by sjclark** [statamic/docs#897]
All over the place there seems to be mention of varying numbers of fieldtypes:
- The **Fieldtypes page says 40+** (https://statamic.dev/reference/fieldtypes) but lists 38.
- The **GitHub page says 40+** (https://github.com/statamic/.github/blob/687d13d37de49a4723aa29aece43a42798468411/profile/README.md?plain=1#L9)
- The **Reference page lists 38** (https://statamic.dev/reference)
- Pricing Page says 40+ (https://statamic.com/pricing) - also it's probably just semantics but some of the fieldtypes aren't actually usable with the free tier (where the count is listed) like Users, User Groups and User Roles?
- Some pages say "Nearly 40" (https://statamic.dev/core-concepts#the-content-schema-is-up-to-you)
- Features Page says "Over 40" (https://statamic.com/features) as does the Laravel page (https://statamic.com/laravel-cms)

Some pages even have it 3 different ways on the same page! 😂 The **Statamic Homepage says 42** (https://statamic.com/) but actually lists 41, and then also says "nearly 40 different".

Just something I stumbled across that should probably be made consistent?

I was considering a PR to make it consistent, but wasn't sure whether there were different definitions depending on whether it was internal or marketing etc?

**Comment by jackmcdade** [comment]
Thanks for this super detailed catch! I've updated the references everywhere except for the docs reference list because we have a few undocumented fieldtypes (float, slug, sites, and taxonomies). That list is dynamic, so the separate task of documenting them will fix that. I'll close this issue now.

Thanks again!

**Comment by sjclark** [comment]
Wooooooooooo! 🔥
