### ISSUE TITLE
"Content Queries": add a link to "Globals"

### ISSUE THREAD

**Issue by schwemmer** [statamic/docs#928]
On the "Content Queries" page, the `GlobalSet` Facade is used as an example: https://statamic.dev/content-queries#repositories

Add a link back to the "Globals" page (https://statamic.dev/globals) for those who need to read up on "Globals" in order to better understand the example.

**Comment by jackmcdade** [comment]
I'm not sure knowing what a GlobalSet is in that context is important, since it's just an example. If you know what they are great, and if you don't, it's okay because we also mention `Entry`.
