### ISSUE TITLE
Explain "Save as HTML" (currently called "Display HTML") option for Bard fieldtype

### ISSUE THREAD

**Issue by schwemmer** [statamic/docs#929]
The explanation text for the toggle button "Display HTML" (should be: "Save as HTML", see here: https://github.com/statamic/cms/issues/6847) gives the following information:

> Save HTML instead of structured data. This simplifies but limits control of your template markup.

This is documented here: https://statamic.dev/fieldtypes/bard#options. Similarly to the explanation in the control panel, the documentation for this reads:
> Save HTML instead of structured data. This simplifies – but limits – control of your template markup. Only works in Bard fields with no defined sets. Default: false.

It should be explained ***how*** the control of your template markup is simplified and ***how*** it is limited when enabling this option. There should be an explanation of uses cases: when would you use "Save as HTML" versus structured data? What are the advantages and disadvantages of each approach?

**Comment by duncanmcclean** [comment]
My guess is that it would probably be better to change the text, instead of documenting that it works differently than expected.

**Comment by schwemmer** [comment]
Yes, of course, and that's why I have created a separate issue here: https://github.com/statamic/cms/issues/6847

But additionally to changing the text, it should also be explained what activating this option means. "This simplifies – but limits – control of your template markup" is too vague.

**Comment by duncanmcclean** [comment]
Ah sorry, didn't read this issue properly. Apologies 🤦‍♂️
