### ISSUE TITLE
'nav' tag undocumented variable and parameter?

### ISSUE THREAD

**Issue by mstratman** [statamic/docs#968]
* `no_results` doesn't seem to be documented.
* The acceptable values or types for the `from` parameter aren't clear

**Comment by mstratman** [comment]
`first` and `last` seem to work, but aren't documented. Perhaps these shouldn't be used though?

**Comment by mstratman** [comment]
'no_results', 'first', and 'last' probably overlap with #808 

'from' is a separate issue.

**Comment by duncanmcclean** [comment]
I've added some clarification - you should pass in the URI of the entry you wish to start the nav from.

We can document the other variables as part of #808.
