### ISSUE TITLE
Docs missing for `{{ user:profile_form }}` and `{{ user:password_form }}`

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/docs#994]
https://github.com/statamic/cms/pull/6400

**Comment by danielfowler** [comment]
Just found out about these tags via Discord since they're not on https://statamic.dev/reference/tags

**Comment by melvicsosa** [comment]
This was a lifesaver, as I spent a couple of hours and was considering an approach that would result in a more complex implemantation.
